# Generated by Django 4.2 on 2024-03-04 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='pic',
            field=models.ImageField(default=None, upload_to='./media/img', verbose_name='img'),
        ),
        migrations.AddField(
            model_name='media',
            name='posts',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='content.post', verbose_name='posts'),
        ),
        migrations.AddField(
            model_name='media',
            name='stories',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='content.story', verbose_name='stories'),
        ),
        migrations.AddField(
            model_name='media',
            name='video',
            field=models.FileField(default=None, upload_to='./media/vid', verbose_name='video'),
        ),
        migrations.AddField(
            model_name='mention',
            name='author',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='mention',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.TextField(default=None, max_length=500, verbose_name='caption'),
        ),
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='story',
            name='caption',
            field=models.TextField(default=None, max_length=500, verbose_name='caption'),
        ),
    ]
