# Generated by Django 4.2 on 2024-03-05 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='story',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='user_activities.comment', verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='story',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to='user_activities.like', verbose_name='likes'),
        ),
        migrations.AddField(
            model_name='story',
            name='media',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='content.media', verbose_name='media'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='user_activities.comment', verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to='user_activities.like', verbose_name='likes'),
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='content.media', verbose_name='media'),
        ),
        migrations.AddField(
            model_name='mention',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='mention',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='user_activities.comment', verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='mention',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to='user_activities.like', verbose_name='likes'),
        ),
        migrations.AddField(
            model_name='mention',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='media',
            name='pics',
            field=models.ManyToManyField(default=None, to='content.picture'),
        ),
        migrations.AddField(
            model_name='media',
            name='videos',
            field=models.ManyToManyField(default=None, to='content.video'),
        ),
    ]
