# Generated by Django 4.2 on 2024-03-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_media_pics_remove_media_videos_picture_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='post',
        ),
        migrations.RemoveField(
            model_name='video',
            name='post',
        ),
        migrations.AddField(
            model_name='media',
            name='pics',
            field=models.ManyToManyField(default=None, related_name='media', to='content.picture'),
        ),
        migrations.AddField(
            model_name='media',
            name='videos',
            field=models.ManyToManyField(default=None, related_name='media', to='content.video'),
        ),
    ]
