# Generated by Django 4.2 on 2024-03-06 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_picture_post_remove_video_post_media_pics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='content.media', verbose_name='media'),
        ),
    ]
