# Generated by Django 4.2 on 2024-03-06 09:32

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_profile_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('ProfObjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
