# Generated by Django 4.2 on 2024-03-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_profile_managers_remove_profile_profid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
    ]
