# Generated by Django 4.2 on 2024-03-05 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=None, verbose_name='text')),
                ('media', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='content.media', verbose_name='media')),
            ],
        ),
    ]
