# Generated by Django 4.2 on 2024-03-04 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_media_pic_media_posts_media_stories_media_video_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('direct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='content.media', verbose_name='media'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='receiver'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='sender'),
        ),
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(default=None, verbose_name='text'),
        ),
    ]
