# Generated by Django 4.2 on 2024-03-04 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_media_pic_media_posts_media_stories_media_video_and_more'),
        ('user_activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='comment',
            name='posts',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='content.post', verbose_name='posts'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default=None, max_length=500, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='like',
            name='comments',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_activities.comment', verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='like',
            name='mentions',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='content.mention', verbose_name='mentions'),
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='content.post', verbose_name='posts'),
        ),
        migrations.AddField(
            model_name='like',
            name='stories',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='content.story', verbose_name='stories'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
